# Generated by Django 4.2.3 on 2023-08-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_education_user_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='set_interest',
            field=models.BooleanField(default=False),
        ),
    ]
